version: "3.8"
services:
    php:
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ../.:/var/www/html
      container_name: php
      networks:
        - laravel-network

    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "8000:80"
      volumes:
        - ../.:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      container_name: nginx
      networks:
        - laravel-network
      depends_on:
        - php

    mysql:
      image: mysql:8.3.0
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        - laravel-network
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "laravel"
        MYSQL_USER: "laravel"
        MYSQL_PASS: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:mysql
      ports:
        - 8080:80
      environment:
        MYSQL_USERNAME: "root"
        MYSQL_ROOT_PASSWORD: "root"
        PMA_HOST: mysql
      networks:
        - laravel-network

networks:
  laravel-network:
    driver: bridge
volumes:
  dbdata:
